[package]
name = "rsa_course_project"
version = "0.1.0"
authors = ["nzaharov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
num = "0.2.1"
image = "0.23.4"
palette = "0.5.0"